<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ3mA8QT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ3mA8QT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ3mA8QT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ3mA8QT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ3mA8QT\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z3mA8QT',
    'container.build_id' => '83b98ece',
    'container.build_time' => 1748113340,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ3mA8QT');
